% === Load prediction results for each model ===
load('bestKNNModel_4Genres.mat', 'YPred_knn', 'YTrue');
load('trainedSVMModel_4Genres.mat', 'YPred_svm','YTrue_svm');
load('trainedBoostedTreeModel.mat', 'YPred_tree','YTest_tree');
%load('A:/DSP_project/Advanced/CNN/genre_cnn_model_4genre.mat', 'YPred_cnn');

% === Define consistent categories ===
targetGenres = ["Folk", "Hip-Hop", "Instrumental", "International"];

% === Convert all predictions and labels to consistent categorical types ===
YTrue       = categorical(string(YTrue), targetGenres);
YPred_knn   = categorical(string(YPred_knn), targetGenres);

% === Display Confusion Matrices ===
figure('Name', 'KNN Confusion Matrix');
confusionchart(YTrue, YPred_knn, ...
    'Title', 'KNN Confusion Matrix', ...
    'RowSummary', 'row-normalized', ...
    'ColumnSummary', 'column-normalized');

figure('Name', 'SVM Confusion Matrix');
confusionchart(YTrue_svm, YPred_svm, ...
    'Title', 'SVM Confusion Matrix', ...
    'RowSummary', 'row-normalized', ...
    'ColumnSummary', 'column-normalized');

figure('Name', 'Boosted Tree Confusion Matrix');
confusionchart(YTest_tree, YPred_tree, ...
    'Title', 'Boosted Tree Confusion Matrix', ...
    'RowSummary', 'row-normalized', ...
    'ColumnSummary', 'column-normalized');

%figure('Name', 'CNN Confusion Matrix');
%confusionchart(YTrue, YPred_cnn, ...
%    'Title', 'CNN Confusion Matrix', ...
%    'RowSummary', 'row-normalized', ...
%    'ColumnSummary', 'column-normalized');
